# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180219_2129_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='featured_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='featured image'),
        ),
    ]
