# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20180221_1050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customrendition',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='customrendition',
            name='image',
        ),
        migrations.RemoveField(
            model_name='img',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='img',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='img',
            name='uploaded_by_user',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='featured_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='featured image'),
        ),
        migrations.DeleteModel(
            name='CustomRendition',
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
