# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20180221_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='client name'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='client_url',
            field=models.URLField(blank=True, null=True, verbose_name='client url'),
        ),
    ]
