# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20180221_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='client_url',
        ),
    ]
