# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('gallery', '0008_auto_20180308_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
    ]
