# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_video_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_code',
            field=models.URLField(blank=True, help_text='z.B. OKRJfIPiJGY. Guck mal: https://support.google.com/youtube/answer/171780?hl=de', null=True, verbose_name='YouTube Code'),
        ),
    ]
