# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20180308_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_code',
            field=models.CharField(blank=True, help_text='z.B. OKRJfIPiJGY. Guck mal: https://support.google.com/youtube/answer/171780?hl=de', max_length=50, null=True, verbose_name='YouTube Code'),
        ),
    ]
