# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_redirectpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedirectPage',
            new_name='PortfolioPage',
        ),
    ]
