# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('base', '0004_landingpage_squashed_0006_auto_20180221_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image', verbose_name='image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='landing_images', to='base.LandingPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
