# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_landingimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='image',
        ),
    ]
